# Config for Dependabot updates. See Documentation here:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "compose/develop/inspector/"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "docker"
    directory: "compose/production/inspector/"
    schedule:
      interval: "daily"
    target-branch: "develop"

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: "/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"
    target-branch: "develop"
